#!/bin/bash

# Create barbucket directory and main collection if they don't exist
if [ ! -d "$HOME/.barbucket/" ]; then
    mkdir ~/.barbucket/
fi
cd ~/.barbucket/ || exit 2
touch ~/.barbucket/main.txt || exit 2

check_if_cancelled () {
    if [[ "$?" != "0" ]]; then
        exit 2
    fi
}

# Check CLI arguments
while getopts "*f:t:" flag; do
        case $flag in
                f) location="$OPTARG";;
                t) out="$OPTARG";;
                *) echo "Invalid options, see the README."; exit 2;;
        esac
done

# Input thought, skip if specified in args
if [[ "$out" == "" ]]; then
    out=$(
        zenity \
        --width 500 --height 100 --title "barbucket 🪣" \
        --entry --text "what's on your mind?" \
        --ok-label "submit ✍️🔥" --cancel-label "trash 🗑️" 2> /dev/null 
    )

    check_if_cancelled;
fi

# File/board selection, skip if specified in args
if [[ "$location" == "" ]]; then
    location=$(
        zenity \
        --title "where to save? 🗃️" --width 150 --height 500 \
        --file-selection --save --filename "$(cd ~/.barbucket/ || exit 2; pwd)""/main.txt" 2> /dev/null
    )

    check_if_cancelled;
fi

# Add thought
echo "$out" >> "$location"

zenity --title "barbucket 🪣" --notification --text "saved thought\"${out:0:15}...\" to ${location}!" 2> /dev/null